# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1680fdd2286fc6d5ab1f61f7c1ac2a8791753d1c6f0344786f86d4bb8d333cb189cf7bfe448e3de60262210df4880005b19bd9f2e050608b37a6adef318991e0

test:
  secret_key_base: 9fd8394c460743c86d2c6c94243f2c2db5ba626e71cf015c2ea6226b96f1dfcc6166b87b89dedde883b9470d7139c839795bf66f07d00e851773f6349c561795

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
